### ISSUE TITLE
Relation's Manager issue

### ISSUE THREAD

**Issue by invaders-xx** [artificertech/filament-multi-context#10]
I have an issue with Context Manager. I didn't change anything except did composer update and now I have issues with relation's manager : Unable to find component:. Do you have the same issue
I don't have that issue in Filament but only in contexts.

FYI I use latest version of Filament, latest L9 and PHP 8.1
The error is :
Unable to find component: [app.filament.admin-context.resources.company-resource.relation-managers.modules-relation-manager]

**Comment by oxytoxin** [comment]
same error encountered

**Comment by coleshirley** [comment]
I am working on this issue. Filament changed how they register components in `2.15.6` which is what caused this to break. Unfortunately this package is very 'hacky' and not easy to adjust. I'm currently working`v2` of this package which should resolve this issue and allow for better maintainability as filament itself changes

**Comment by coleshirley** [comment]
Filament-Multi-Context v2.0.0-beta1 is now released. Since this is a complete rework there will be some refactoring for users of this package. Hopefully the README is clear. If there are support questions please ask them in the discord channel. https://discord.com/channels/883083792112300104/968620931117383710
