### ISSUE TITLE
some missing feature

### ISSUE THREAD

**Issue by mrezauli** [artificertech/filament-multi-context#7]
Your hard work inspired me!!! Thanks!!!
1. Console command for generating context-wise page / resource / widgets

**Comment by coleshirley** [comment]
This is in the works!

**Comment by coleshirley** [comment]
After looking into this more the current filament commands are not easy to override. I would have to maintain copies of each command.

This is extra work I don't care for since now in v2 adding newly-generated resources to a different context is as simple as cutting, pasting, and changing the namespace
