### ISSUE TITLE
Demo Application

### ISSUE THREAD

**Issue by ManojKiranAppathurai** [artificertech/filament-multi-context#9]
Demo Application with

1. Multiple Guards
2. Multiple Login page

**Comment by coleshirley** [comment]
This is outside the scope of the package. Contexts provide groups of Resources, Pages, and Widgets that can be configured in the Context class. 

You can configure your own middleware on a context if you want a separate guard for all routes in a context. 

The base filament login page is registered separately from Resources, Pages, and Widgets because all filament pages require an authenticated user to be accessed. Contexts follow the same pattern so it makes no sense to have a login page inside of a context. You need to create a custom route for it in your specific app
